DOCKER_BUILDKIT should just be set external to the build if used. Make things work with current upstream again.

diff --git a/tools/bld b/tools/bld
--- a/tools/bld
+++ b/tools/bld
@@ -6,13 +6,13 @@
 #  3) Versions starting with "exp_" will not be tagged or pushed as "latest".
 #  4) Versions starting with "nopush_" will not be pushed at all.
 IMAGE=$(  grep name\= Dockerfile | \
-	      head -1 | \
-	      sed -e    's/name=\"\(.*\)\"/\1/' | \
-	      tr -d '[[:space:]]' | tr -d '\\' )
+          head -1 | \
+          sed -e    's/name=\"\(.*\)\"/\1/' | \
+          tr -d '[[:space:]]' | tr -d '\\' )
 VERSION=$(grep version\= Dockerfile | \
-	      head -1 | \
-	      sed -e 's/version=\"\(.*\)\"/\1/' | \
-	      tr -d '[[:space:]]' | tr -d '\\' )
+          head -1 | \
+          sed -e 's/version=\"\(.*\)\"/\1/' | \
+          tr -d '[[:space:]]' | tr -d '\\' )
 if [ -z "${IMAGE}" ]; then
     echo 1>&2 "Could not determine name from Dockerfile."
     exit 2
@@ -25,21 +25,13 @@ squash=""
 if [ -n "${SQUASH}" ]; then
     squash="--squash"
 fi
-DOCKER_BUILDKIT=1 # Use buildkit if available; if not, ignored.
-# Except that if you're running Docker unprivileged, then you may
-#  get "buildkit not supported by daemon"...
-export DOCKER_BUILDKIT
+# You probably want to set DOCKER_BUILDKIT in your environment if your
+#  Docker supports it.
 docker build ${squash} -t ${IMAGE}:${VERSION} .
 rc=$?
 if [ "${rc}" -ne 0 ]; then
-    unset DOCKER_BUILDKIT
-    echo "Docker with buildkit failed; trying without."
-    docker build ${squash} -t ${IMAGE}:${VERSION} .
-    rc=$?
-    if [ "${rc}" -ne 0 ]; then
-	echo 1>&2 "Docker build failed."
-	exit 1
-    fi
+    echo 1>&2 "Docker build failed."
+    exit 1
 fi
 EXPERIMENTAL=0
 etag=$(echo "${VERSION}" | cut -d '_' -f 1)
@@ -54,21 +46,21 @@ if [ "${EXPERIMENTAL}" -ne 1 ]; then
     ichar=$(echo "${VERSION}" | cut -c 1)
     itype=""
     case $ichar in
-	"r")
-	    itype="release"
-	    ;;
-	"w")
-	    itype="weekly"
-	    ;;
-	"d")
-	    itype="daily"
-	    ;;
-	*)
-	    ;;
+    "r")
+        itype="release"
+        ;;
+    "w")
+        itype="weekly"
+        ;;
+    "d")
+        itype="daily"
+        ;;
+    *)
+        ;;
     esac
     if [ -n "$itype" ]; then
-	docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest_${itype}
-	docker push ${IMAGE}:latest_${itype}
+    docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest_${itype}
+    docker push ${IMAGE}:latest_${itype}
     fi
     docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest
     docker push ${IMAGE}:latest
